stages:
  - build_and_test

variables:
  GIT_DEPTH: 1
  BUILDER_IMAGE_TAG: "@sha256:a31b6f9175247e0f761f043e1605d4fe39e50ddc86d8f960e270d9d3e71f2b3a"

hive_fork_manager:
  stage: build_and_test
  image: "$CI_REGISTRY_IMAGE/builder$BUILDER_IMAGE_TAG"
  script:
    - /etc/init.d/postgresql start
    - mkdir -p "$CI_JOB_NAME"/build
    - cd "$CI_JOB_NAME"/build
    - cmake ../..
    - make extension.hive_fork_manager
    - make install
    - ctest --output-on-failure  -R test.functional.hive_fork_manager.*
  tags:
    - public-runner-docker

c++_unit_tests:
  stage: build_and_test
  image: "$CI_REGISTRY_IMAGE/builder$BUILDER_IMAGE_TAG"
  script:
    - mkdir -p "$CI_JOB_NAME"/build
    - cd "$CI_JOB_NAME"/build
    - cmake ../..
    - make
    - ctest --output-on-failure -R test.unit.*
  tags:
    - public-runner-docker