stages:
  - build_and_test

variables:
  GIT_DEPTH: 1
  GIT_SUBMODULE_STRATEGY: recursive
  BUILDER_IMAGE_TAG: "@sha256:370887eb9d2b95162513987060bec7dd10f4d2fb80adbec70fb83bd601786fa5"

hive_fork_manager:
  stage: build_and_test
  image: "$CI_REGISTRY_IMAGE/builder$BUILDER_IMAGE_TAG"
  script:
    - /etc/init.d/postgresql start
    - mkdir -p "$CI_JOB_NAME"/build
    - cd "$CI_JOB_NAME"/build
    - cmake -DCMAKE_BUILD_TYPE=Release ../..
    - make extension.hive_fork_manager -j10
    - make install
    - ctest --output-on-failure  -R test.functional.hive_fork_manager.*
  tags:
    - public-runner-docker

hived:
  stage: build_and_test
  image: "$CI_REGISTRY_IMAGE/builder$BUILDER_IMAGE_TAG"
  script:
    - /etc/init.d/postgresql start
    - mkdir -p "$CI_JOB_NAME"/build
    - cd "$CI_JOB_NAME"/build
    - cmake -DCMAKE_BUILD_TYPE=Release -DCLEAR_VOTES=ON -DENABLE_MIRA=OFF -DBUILD_HIVE_TESTNET=OFF -DHIVE_LINT=OFF ../..
    - make hived -j10
    # check if sql_serializer compiles with hived
    - test -f hive/libraries/plugins/sql_serializer/libsql_serializer_plugin.a
    # check if sql_serializer plugin is included in hived plugins
    - cd ./hive/programs/hived
    - ./hived --help | grep psql-url
  tags:
    - public-runner-docker
