stages:
  - build_and_test

variables:
  GIT_DEPTH: 1
  GIT_SUBMODULE_STRATEGY: recursive
  BUILDER_IMAGE_TAG: "@sha256:370887eb9d2b95162513987060bec7dd10f4d2fb80adbec70fb83bd601786fa5"

hive_fork_manager:
  stage: build_and_test
  image: "$CI_REGISTRY_IMAGE/builder$BUILDER_IMAGE_TAG"
  script:
    - /etc/init.d/postgresql start
    - mkdir -p "$CI_JOB_NAME"/build
    - cd "$CI_JOB_NAME"/build
    - cmake -DCMAKE_BUILD_TYPE=Release ../..
    - make extension.hive_fork_manager -j10
    - make install
    - ctest --output-on-failure  -R test.functional.hive_fork_manager.*
  tags:
    - public-runner-docker

# c++_unit_tests:
#   stage: build_and_test
#   image: "$CI_REGISTRY_IMAGE/builder$BUILDER_IMAGE_TAG"
#   script:
#     - mkdir -p "$CI_JOB_NAME"/build
#     - cd "$CI_JOB_NAME"/build
#     - cmake -DCMAKE_BUILD_TYPE=Release ../..
#     - make
#     - ctest --output-on-failure -R test.unit.*
#   tags:
#     - public-runner-docker